// @ts-check

/** @type {import('@stryker-mutator/api/core').PartialStrykerOptions} */
module.exports = {
  mutate: [
    'packages/mysql/src/mysql-value-reader.ts',
    'packages/cli/src/cli-rename-hints.ts',
    'packages/core/src/tracking/snapshot-value-equality.ts',
    'packages/core/src/migrations/model-diff-operation-description.ts',
    'packages/core/src/migrations/migration-column-builder.ts',
    'packages/core/src/restoration-actions.ts',
    'packages/core/src/restoration-scope.ts',
    'packages/core/src/restoration-failure-inspection.ts',
    'packages/core/src/failure-atomic-property-write.ts',
    'packages/core/src/property-value-restoration.ts',
    'packages/core/src/verified-property-write.ts',
    'packages/core/src/tracking/verified-navigation-write.ts',
    'packages/core/src/tracking/entity-entry-concurrency.ts:68-78',
    'packages/core/src/tracking/entity-entry-concurrency.ts:85-104',
    'packages/core/src/tracking/entity-entry-concurrency-application.ts',
    'packages/core/src/tracking/entity-entry-concurrency-operation.ts',
    'packages/core/src/tracking/entity-entry-version-sync.ts:16-23',
    'packages/core/src/tracking/entity-entry-version-sync.ts:33-46',
    'packages/core/src/tracking/concurrency-restoration-journal.ts:17-70',
    'packages/core/src/materialization/complex-value-materializer.ts:35-41',
    'packages/core/src/materialization/complex-value-materializer.ts:52-58',
    'packages/core/src/materialization/complex-property-path-write.ts',
    'packages/core/src/core/created-ancestor-restoration.ts',
    // Keep stateful modules focused on their release-critical write/rollback seams.
    'packages/core/src/core/save-time-mutations.ts:63-86',
    'packages/core/src/core/save-time-mutations.ts:127-130',
    'packages/core/src/core/save-time-tenant.ts:57-72',
    'packages/core/src/core/save-time-tenant.ts:100-112',
    'packages/core/src/core/bulk-write-tenant.ts:53-64',
    'packages/core/src/core/bulk-write-tenant.ts:80-83',
    'packages/core/src/core/unit-of-work/generated-value-writer.ts:82-98',
    'packages/core/src/core/unit-of-work/tracked-version-acceptance.ts:37-75',
    'packages/core/src/tracking/change-tracker-detection.ts:85-92',
    'packages/core/src/tracking/relationship-detection-restore.ts:18-32',
    'packages/core/src/tracking/relationship-detection-restore.ts:36-40',
    'packages/core/src/tracking/restorable-value-snapshot.ts',
    'packages/core/src/tracking/navigation-write-journal.ts',
    'packages/core/src/tracking/navigation-value-restoration.ts',
    'packages/core/src/tracking/navigation-collection-copy.ts',
    'packages/core/src/tracking/navigation-load-checkpoint.ts:38-114',
    'packages/core/src/tracking/navigation-load-operation.ts:24-35',
    'packages/core/src/tracking/navigation-load-tracker-journal.ts:76-135',
    'packages/core/src/tracking/navigation-load-ownership.ts',
    'packages/core/src/tracking/navigation-load-ownership-checkpoint.ts:82-122',
    'packages/core/src/tracking/navigation-load-ownership-comparison.ts:48-149',
    'packages/core/src/tracking/navigation-load-ownership-facts.ts',
    'packages/core/src/tracking/entity-entry-snapshot.ts:21-24',
    'packages/core/src/core/many-to-many-change-set.ts:102-106',
    'packages/core/src/query/include-navigation-loaded-state.ts',
    'packages/core/src/query/include-loader.ts:47-70',
    'packages/core/src/failure-atomic-navigation-write.ts',
    'packages/core/src/tracking/loaded-reference-fixup.ts',
    'packages/core/src/core/many-to-many-change-set.ts:31-45',
    'packages/core/src/core/navigation-link-ops.ts:53-97',
    'packages/core/src/query/include-loader-stitch.ts',
    'packages/core/src/query/include-many-to-many-stitch.ts',
    'packages/core/src/tracking/tracked-acceptance-journal.ts:53-71',
    'packages/core/src/materialization/complex-value-materializer.ts:66-78',
    'packages/core/src/core/policy-property-path.ts:21-36',
    'packages/core/src/core/save-plan-inspection.ts',
    'packages/core/src/core/save-plan-builder.ts:43-58',
    'packages/core/src/core/save-time-writes.ts:43-49',
    'packages/core/src/core/save-time-relationship-reconciliation.ts:44-70',
    'packages/core/src/core/save-time-relationship-generation-values.ts:52-59',
  ],
  // The sandbox only ever runs the mutation suite, which resolves
  // `@entitykit/*` to package SOURCES. Copying the compiled output and the
  // coverage reports hauls thousands of files per run for nothing.
  ignorePatterns: ['packages/*/dist', 'coverage'],
  testRunner: 'jest',
  jest: {
    projectType: 'custom',
    configFile: 'jest.mutation.config.cjs',
    enableFindRelatedTests: true,
  },
  coverageAnalysis: 'perTest',
  ignoreStatic: true,
  concurrency: 2,
  reporters: ['clear-text', 'progress', 'html', 'json'],
  htmlReporter: {
    fileName: 'coverage/mutation.html',
  },
  jsonReporter: {
    fileName: 'coverage/mutation.json',
  },
  thresholds: {
    high: 95,
    low: 90,
    break: 90,
  },
  tempDirName: 'temp/stryker',
  timeoutMS: 10_000,
};
