import type { IdentityColumnOptions, RowIdColumnOptions } from '../model/store-generation';
import type { SqlDialect } from '../sql/sql-dialect';
import { MigrationBuilder as MigrationBuilderImplementation } from './migration-builder';
import type {
    MigrationAlterColumnDefinition,
    MigrationBuilderOptions,
    MigrationColumnDefinition,
    MigrationCreateTableOptions,
    MigrationDropIndexOptions,
    MigrationForeignKeyDefinition,
    MigrationIndexDefinition,
    MigrationSequenceDefinition,
    MigrationSqlOptions,
    MigrationStatement,
    MigrationTableRebuildDefinition,
} from './migration-builder-types';

/** Fluent configuration for one column in a newly created table. */
export interface MigrationColumnBuilder {
    /** Perform the nullable operation. */ nullable(): this;
    /** Perform the not null operation. */ notNull(): this;
    /** Perform the primary key operation. */ primaryKey(): this;
    /** Perform the default sql operation. */ defaultSql(sql: string): this;
    /** Perform the computed sql operation. */ computedSql(sql: string, stored?: boolean): this;
    /** Perform the collation operation. */ collation(name: string): this;
    /** Perform the generated by identity operation. */ generatedByIdentity(options?: IdentityColumnOptions): this;
    /** Perform the generated by auto increment operation. */ generatedByAutoIncrement(): this;
    /** Perform the generated by row id operation. */ generatedByRowId(options?: RowIdColumnOptions): this;
    /** Perform the generated by sequence operation. */ generatedBySequence(name: string, schemaName?: string): this;
}

/** Fluent configuration for columns in a newly created table. */
export interface MigrationTableBuilder {
    /** Perform the column operation. */ column(name: string, type: string): MigrationColumnBuilder;
}

/** Callback used to declare the columns in a new table. */
export type MigrationTableCallback = (table: MigrationTableBuilder) => void;

/** Stable migration-operation contract supplied to `Migration.up` and `down`. */
export interface MigrationBuilder {
    /** The statements. */ readonly statements: readonly MigrationStatement[];
    /** The requires table rebuild. */ readonly requiresTableRebuild: boolean;
    /** Whether alter table constraints. */ readonly canAlterTableConstraints: boolean;
    /** Perform the sql operation. */ sql(text: string, values?: readonly unknown[] | MigrationSqlOptions, options?: MigrationSqlOptions): this;
    /** Create schema. */ createSchema(schemaName: string): this;
    /** Perform the drop schema operation. */ dropSchema(schemaName: string): this;
    /** Create table. */ createTable(tableName: string, columns: readonly MigrationColumnDefinition[] | MigrationTableCallback, schemaName?: string, options?: MigrationCreateTableOptions): this;
    /** Perform the drop table operation. */ dropTable(tableName: string, schemaName?: string): this;
    /** Perform the rename table operation. */ renameTable(tableName: string, newTableName: string, schemaName?: string): this;
    /** Create extension. */ createExtension(extensionName: string, schemaName?: string): this;
    /** Perform the drop extension operation. */ dropExtension(extensionName: string): this;
    /** Perform the add primary key operation. */ addPrimaryKey(tableName: string, constraintName: string, columns: readonly string[], schemaName?: string): this;
    /** Perform the drop primary key operation. */ dropPrimaryKey(tableName: string, constraintName: string, schemaName?: string): this;
    /** Perform the add unique constraint operation. */ addUniqueConstraint(tableName: string, constraintName: string, columns: readonly string[], schemaName?: string): this;
    /** Perform the drop unique constraint operation. */ dropUniqueConstraint(tableName: string, constraintName: string, schemaName?: string): this;
    /** Create index. */ createIndex(index: MigrationIndexDefinition): this;
    /** Perform the drop index operation. */ dropIndex(indexName: string, schemaName?: string, options?: MigrationDropIndexOptions): this;
    /** Perform the rename index operation. */ renameIndex(indexName: string, newIndexName: string, schemaName?: string): this;
    /** Perform the add foreign key operation. */ addForeignKey(foreignKey: MigrationForeignKeyDefinition): this;
    /** Perform the drop foreign key operation. */ dropForeignKey(tableName: string, constraintName: string, schemaName?: string): this;
    /** Perform the add check constraint operation. */ addCheckConstraint(tableName: string, constraintName: string, sql: string, schemaName?: string): this;
    /** Perform the drop check constraint operation. */ dropCheckConstraint(tableName: string, constraintName: string, schemaName?: string): this;
    /** Perform the add column operation. */ addColumn(tableName: string, column: MigrationColumnDefinition, schemaName?: string): this;
    /** Perform the drop column operation. */ dropColumn(tableName: string, columnName: string, schemaName?: string): this;
    /** Perform the rename column operation. */ renameColumn(tableName: string, columnName: string, newColumnName: string, schemaName?: string): this;
    /** Perform the alter column operation. */ alterColumn(tableName: string, column: MigrationAlterColumnDefinition, schemaName?: string): this;
    /** Create sequence. */ createSequence(sequence: MigrationSequenceDefinition): this;
    /** Perform the alter sequence operation. */ alterSequence(sequence: MigrationSequenceDefinition, previous: MigrationSequenceDefinition): this;
    /** Perform the drop sequence operation. */ dropSequence(sequence: MigrationSequenceDefinition): this;
    /** Perform the rebuild table operation. */ rebuildTable(definition: MigrationTableRebuildDefinition): this;
}

/** Factory used by providers to create migration operation collectors. */
export type MigrationBuilderFactory = () => MigrationBuilder;

/** Public constructor shape; the concrete staged implementation stays private. */
export type MigrationBuilderConstructor = new(
    dialect?: SqlDialect,
    options?: MigrationBuilderOptions,
) => MigrationBuilder;

/** Public constructor; the staged concrete inheritance graph remains private. */
export const MigrationBuilder: MigrationBuilderConstructor = MigrationBuilderImplementation;
